### ISSUE TITLE
grep recursive?

### ISSUE THREAD

**Issue by mdbergmann** [nibbula/lish#11]
Hi.

I couldn't find how to find results recursive using the built-in grep command.
It seems that `grep-files` in `grep.lisp` knows recursive, but the lish command doesn't have the flag.

**Comment by nibbula** [comment]
It looks like I was planning to add that, but didn't yet. In the meantime workarounds can be:

```
grep "foo" **/*.lisp
find -c "\\.lisp$" | grep -s "foo"
```

I'll see if I can add a `-r` shortly.

**Comment by nibbula** [comment]
This commit in yew should add `-r` to `grep`.

https://github.com/nibbula/yew/commit/e2ca296b4f52e0e15bba820797c8b89dc5b51c24

I haven't tested it extensively yet.

**Comment by mdbergmann** [comment]
Excellent. Seems to work.

**Comment by nibbula** [comment]
Thanks!
