### ISSUE TITLE
Hitting tab for path completion breaks

### ISSUE THREAD

**Issue by mdbergmann** [nibbula/lish#12]
Hi.

Sometimes, or often actually (often enough to file a bug report :), I want to type a command, like `diff` and start typing the path to the file. Then I want to auto complete the path by hitting TAB, but lish then breaks with:

```
mbergmann@katalah ~/Downloads$ diff SH[TAB]
Must have a file name.
```

**Comment by nibbula** [comment]
Sorry about that. I'm guessing you're on macOS. I'm aware of the bug.
The main issue is I haven't come up with a file content detection that works on all platforms.
I'll try to have a workaround fix soon.

**Comment by nibbula** [comment]
Hopefully this patch fixes the problem:
https://github.com/nibbula/yew/commit/33da6d5d6e4fff9762598b9208ff36a169a0c6b9

I'm planning on eventually having a better longer term solution.

**Comment by mdbergmann** [comment]
Yes, I'm on macOS.
The workaround seems to work nicely (as far as I could test).

**Comment by nibbula** [comment]
Nice. Thanks.
