### ISSUE TITLE
Many spaces with emacs shell

### ISSUE THREAD

**Issue by Hectarea1996** [nibbula/lish#15]
I was trying to use lish with emacs shell mode, but something weird is happening. Each time the shell is asking me for a command, a lot of spaces are printed after the $ sign. Here is an image:

![lish](https://github.com/nibbula/lish/assets/17879146/cefc097a-fa91-4784-a715-68ce5a05b264)

See how far the cursor is from the dollar sign. I don't know if this is an Emacs or Lish error, but maybe you can get an idea of what is happening.

Thanks for making this project!!

**Comment by nibbula** [comment]
Thanks for reportinng this. A quick workaround is to start with "lish -t dumb", but it's a bug that it doesn't pick the correct terminal type by default when running under Emacs. I don't run it under Emacs, so I forgot about it. I'll put in a fix shortly.

**Comment by nibbula** [comment]
I think commit [046d480](https://github.com/nibbula/yew/commit/7d59a2b5df901f3a12691d9187495926421cd082) in yew should fix this.

**Comment by Hectarea1996** [comment]
Thank you!! It's working now.

**Comment by nibbula** [comment]
Thanks. Feel free to let me know any other problems or questions.
