### ISSUE TITLE
-n still loads init file

### ISSUE THREAD

**Issue by mdbergmann** [nibbula/lish#7]
Hello.

I've created an init file as ~/.lishrc.
When executing `lish -n` it still seems to load the file.

```
❯ lish -n    
Welcome to Lish 0.1.88
Setting up aliases...
Check 1
```

**Comment by nibbula** [comment]
It should be fixed in
[4731a05](https://github.com/nibbula/lish/commit/4731a054da9a26f88febab3336934d992d2bee30)

Thanks for reporting.

**Comment by mdbergmann** [comment]
It works, thanks.
