### ISSUE TITLE
How to expand $PATH

### ISSUE THREAD

**Issue by mdbergmann** [nibbula/lish#8]
Hello.

This is just a question:

It seems that `export PATH "$PATH:foo"` doesn't work.

What is the proposed way to expand shell/environment variables?
`nos:env` together with `setf` and could probably work. But just wondering is there if a simpler way?

**Comment by nibbula** [comment]
Double quotes are much simpler than in POSIX shells, and act like Common Lisp double quotes, so no expansion happens inside them. Instead one can write it without quotes:

`export PATH $PATH:foo`

The equivalent in Lisp could be:

`(setf (nos:command-path-list) (append (nos:command-path-list) '("foo")))`

which has the advantage maybe working on other platforms like Windows. I wouldn't recommend it, but for unix only using `nos:env` and `dlib:s+` you could say:

`(setf (nos:env "PATH") (dlib:s+ (nos:env "PATH") ":foo"))`

**Comment by mdbergmann** [comment]
Thanks.
This is pretty neat.
