### ISSUE TITLE
Can't find commands in PATH

### ISSUE THREAD

**Issue by mdbergmann** [nibbula/lish#9]
Hi.

Sorry for all the questions this morning.

I have "/usr/local/bin" in PATH, so `echo $PATH` shows it in lish.

But executing commands that are in this path are not found. I.e. `rlwrap` is in /usr/local/bin.
Does lish look in all PATHs?

**Comment by nibbula** [comment]
You're quite welcome to ask questions. I probably should have written some documentation already.

It should find things in all elements of PATH. But, like other shells, if you have tried to run the command in from different diretory in the PATH, it may have saved the location, and you might have to `hash -r` to forget about the old location.

Also there was a recent bug in the opsys library where it wasn't recognizing symbolic links as commands, which I just fixed. If this was affecting you, you might have to update and rebuild. Sorry about that.

**Comment by mdbergmann** [comment]
> Also there was a recent bug in the opsys library where it wasn't recognizing symbolic links as commands, which I just fixed. If this was affecting you, you might have to update and rebuild. Sorry about that.

No prob. But I think this might be it. Homebrew on macOS creates lots of symlinks in /usr/local/bin.

**Comment by mdbergmann** [comment]
Works now, thanks.

**Comment by mdbergmann** [comment]
This can be closed I guess?
